services:
  img:
    image: unit:python3.13
    container_name: img
    working_dir: /app
    environment:
      - TZ=Europe/Paris
    ports:
      - "8081:80"
    volumes:
      - ./app:/app:rw
      - ./config/config.json:/docker-entrypoint.d/config.json:ro
    command: /app/start.sh
